#include "player.h"

#include <iostream>

int main()
{
  // DO NOT EDIT THIS FILE

  // Create one instance of player using default constructor
  Player p1;

  // Create another instance of player using non-default constructor
  Player p2("Les", 20, 10, 6, 0, 0);

  // Call the 'player_move' method on p1 ten times
  for (int i = 0; i < 10; i++)
  {
    p1.PlayerMove();
  }

  // Call 'display_stat' method on p1
  p1.DisplayStat();
  std::cout << "\n";

  // Call 'display_stat' method on p2
  p2.DisplayStat();
  std::cout << "\n";

  // Call 'take_damage' method on p1
  p1.TakeDamage(25);
  std::cout << "\n";

  // Call 'display_stat' method on p1
  p1.DisplayStat();

  return 0;
}
